command:
  - gunicorn
  - -w
  - "1"
  - -k
  - uvicorn.workers.UvicornWorker
  - app:app

env:
  - name: DATABRICKS_HOST
    value: https://dbc-50714363-3e5b.cloud.databricks.com
  - name: LLM_ENDPOINT_NAME
    value: databricks-gpt-oss-120b
  - name: VECTOR_SEARCH_ENDPOINT
    value: ai-tool-vector-endpoint
  - name: VECTOR_INDEX_NAME
    value: workspace.default.ai_tool_profiles_index
  - name: MLFLOW_EXPERIMENT_ID
    valueFrom: 1629242548014964